<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="InetbankingV1" duration-ms="450562" started-at="2020-06-29T03:46:04Z" finished-at="2020-06-29T03:53:35Z">
    <groups>
    </groups>
    <test name="TestNG" duration-ms="450562" started-at="2020-06-29T03:46:04Z" finished-at="2020-06-29T03:53:35Z">
      <class name="com.banking.TestCases.TestCaseDDT">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="setUp" is-config="true" duration-ms="32835" started-at="2020-06-29T03:48:25Z" finished-at="2020-06-29T03:48:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="loginDDT" duration-ms="18360" started-at="2020-06-29T03:49:01Z" data-provider="LoginData" finished-at="2020-06-29T03:49:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr268483]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[yhEbyty]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method status="FAIL" signature="loginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="loginDDT" duration-ms="20405" started-at="2020-06-29T03:49:19Z" data-provider="LoginData" finished-at="2020-06-29T03:49:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ghdkfnd]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ccsdfsdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.banking.TestCases.TestCaseDDT.loginDDT(TestCaseDDT.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method status="FAIL" signature="loginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="loginDDT" duration-ms="28236" started-at="2020-06-29T03:49:40Z" data-provider="LoginData" finished-at="2020-06-29T03:50:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dsdsfdf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ccdsshgfgf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.banking.TestCases.TestCaseDDT.loginDDT(TestCaseDDT.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method status="FAIL" signature="loginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="loginDDT" duration-ms="36508" started-at="2020-06-29T03:50:08Z" data-provider="LoginData" finished-at="2020-06-29T03:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[erertr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[rtrtrg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.banking.TestCases.TestCaseDDT.loginDDT(TestCaseDDT.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method status="PASS" signature="loginDDT(java.lang.String, java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="loginDDT" duration-ms="88252" started-at="2020-06-29T03:50:44Z" data-provider="LoginData" finished-at="2020-06-29T03:52:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr268483]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[yhEbyty]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDDT -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.banking.TestCases.TestCaseDDT@a4102b8]" name="tearDown" is-config="true" duration-ms="825" started-at="2020-06-29T03:52:13Z" finished-at="2020-06-29T03:52:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.banking.TestCases.TestCaseDDT -->
      <class name="com.banking.TestCases.TestCase001">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.banking.TestCases.TestCase001@d83da2e]" name="setUp" is-config="true" duration-ms="124081" started-at="2020-06-29T03:46:05Z" finished-at="2020-06-29T03:48:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testCase()[pri:0, instance:com.banking.TestCases.TestCase001@d83da2e]" name="testCase" duration-ms="9165" started-at="2020-06-29T03:48:09Z" finished-at="2020-06-29T03:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.banking.TestCases.TestCase001@d83da2e]" name="tearDown" is-config="true" duration-ms="6691" started-at="2020-06-29T03:48:18Z" finished-at="2020-06-29T03:48:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.banking.TestCases.TestCase001 -->
      <class name="com.banking.TestCases.TestCaseAdd002">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.banking.TestCases.TestCaseAdd002@11dc3715]" name="setUp" is-config="true" duration-ms="25655" started-at="2020-06-29T03:52:14Z" finished-at="2020-06-29T03:52:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="addNewCustomer()[pri:0, instance:com.banking.TestCases.TestCaseAdd002@11dc3715]" name="addNewCustomer" duration-ms="54834" started-at="2020-06-29T03:52:39Z" finished-at="2020-06-29T03:53:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.banking.TestCases.TestCaseAdd002@11dc3715]" name="tearDown" is-config="true" duration-ms="670" started-at="2020-06-29T03:53:34Z" finished-at="2020-06-29T03:53:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.banking.TestCases.TestCaseAdd002 -->
    </test> <!-- TestNG -->
  </suite> <!-- InetbankingV1 -->
</testng-results>
